# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver import ChromeOptions
from selenium.webdriver.common.by import By
import csv
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = ChromeOptions()
options.add_argument("user-data-dir=C:/Users/Audrey/AppData/Local/Google/Chrome/User Data")
driver = webdriver.Chrome(options=options)
driver.implicitly_wait(10) #seconds
driver.set_window_size(1115, 799)
driver.get("https://photos.google.com")
body=driver.find_element(By.CLASS_NAME,'EIlDfe')

waitO=WebDriverWait(driver,3)
for x in range(0,1472):
    waitO.until(EC.element_to_be_clickable(driver.find_element(By.CLASS_NAME,'EIlDfe')))
    body.send_keys(Keys.ARROW_RIGHT)
    
waitO=WebDriverWait(driver,3)
waitO.until(EC.visibility_of_element_located(body))
driver.find_element(By.CLASS_NAME,'EIlDfe').send_keys(Keys.ARROW_RIGHT)